### ISSUE TITLE
Add Rust

### ISSUE THREAD

**Issue by shubheksha** [freeCodeCamp/how-to-contribute-to-open-source#26]
https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md
Issue label: [E-easy](https://github.com/rust-lang/rust/issues?q=is%3Aissue+is%3Aopen+label%3AE-easy)

**Comment by ryzokuken** [comment]
@shubheksha I wanted to solve this as my first issue here... Could you please elaborate on the issue? Where do I add the Rust project? Perhaps some list of beginner-friendly projects?

**Comment by ravk1234** [comment]
Can I solve this issue?

**Comment by erictleung** [comment]
@ravk1234 are you referring to [this PR](https://github.com/freeCodeCamp/how-to-contribute-to-open-source/pull/157)? If so, you've closed it yourself.

But I'd kindly ask that you let others contribute and fix this issue for two reasons. Your PR looks like it has some extra commits that will need to be fixed on the command line. And second, this issue is reserved for first-time contributors so that they can get low-risk way to contribute to open-source. I hope you understand. Take a look at the [Contributing to open source in general](https://github.com/freeCodeCamp/how-to-contribute-to-open-source#contributing-to-open-source-in-general) for more opportunities around GitHub to contribute. Happy coding!
