### ISSUE TITLE
Translation into Urdu

### ISSUE THREAD

**Issue by AliSheheryar** [freeCodeCamp/how-to-contribute-to-open-source#485]
Hello coders, I hope you are having a great day. I am new to open source contribution and i want to start off with **Urdu** language(Pakistani National Language) translation of readme.

**Comment by erictleung** [comment]
@AliSheheryar great! Looking forward to your contribution. I don't know Urdu, so when you make a pull request to this repository, please try to find someone else who knows Urdu review your changes if possible. Otherwise, I'll simply create another issue to help review it.

If you are going to create this translation, please name the file `README-UR.md`

**Comment by AliSheheryar** [comment]
Thanks eric for your support. I'll  get right to it. Ahoy!

**Comment by iem-saad** [comment]
Hi! @erictleung @AliSheheryar , I hope you are doing good. Is the translation in Urdu done? If yes I can volunteer for review and in case you are not working on this, I am also translating in Urdu and it will be completed by tomorrow.

Thanks.
