### ISSUE TITLE
Change direct GitHub search's links

### ISSUE THREAD

**Issue by BobinMathew** [freeCodeCamp/how-to-contribute-to-open-source#498]
![image](https://user-images.githubusercontent.com/32351527/103433625-77efd880-4c1a-11eb-88f1-4ff2354a4c43.png)

Currently this links are leading to Search.

Since there is an issue based search bar why cant this links go to that space?
This will be more convenient for users for searching.

What do you guys think?

**Comment by erictleung** [comment]
Thanks for the comment! Can you give an example or screenshot of what you mean by "issue based search bar"? I'm unsure on what you mean by it.

**Comment by BobinMathew** [comment]
![osp_pic2](https://user-images.githubusercontent.com/32351527/104752633-e9806880-577c-11eb-94e1-dc2befa75f3a.png)
I meant this page

**Comment by erictleung** [comment]
Oh I see, through the URL https://github.com/issues. I'm assuming that this functionality will be kept, so that sounds like a good task to convert them to the issue-specific search. It does appear to reduce some noise of the other search.

The one piece of caveat is that the issues tab loses the ability to filter on programming language. But given these are beginners, most of these beginner issues may be more documentation related so programming language might not be much of a barrier.

I'll keep this open in case people want to change it to the Issues tab. That is fine by me.

**Comment by BobinMathew** [comment]
@erictleung may I do this task
