### ISSUE TITLE
Translating the Readme file to French

### ISSUE THREAD

**Issue by BKD471** [freeCodeCamp/how-to-contribute-to-open-source#510]
I really want to translate the Readme file to French..can i help you

**Comment by adityatiwari18** [comment]
The readme is already translated to [french](https://github.com/freeCodeCamp/how-to-contribute-to-open-source/blob/master/README-FR.md)

**Comment by erictleung** [comment]
@BKD471 thanks for the enthusiasm to contribute, but as @adityatiwari18 has pointed out, the README is already translated to French.

Feel free to help translate parts of the English version to French that are missing from the French translation that may have happened because new resources are added. Happy coding!
