### ISSUE TITLE
Adding a readme file in Hindi language 

### ISSUE THREAD

**Issue by Jeevan-Kiran-Lenka** [freeCodeCamp/how-to-contribute-to-open-source#540]
Heya! 

I believe that there should be a **Hindi Readme** as **43.63%** of the world's population speaks Hindi so I guess it will be nice to have it here and [how-to-contribute-to-open-source](https://github.com/freeCodeCamp/how-to-contribute-to-open-source) repo doesn't have it.

[percentage of people in the world who speaks hindi](https://www.google.com/search?q=peracntage+of+people+in+the+world+whos+speaks+hindi&oq=peracntage+of+people+in+the+world+whos+speaks+hindi&aqs=chrome..69i57.12040j0j7&sourceid=chrome&ie=UTF-8)

**Comment by Jeevan-Kiran-Lenka** [comment]
Heya! I can add README-HI to your repo and I would like to have that chance

**Comment by erictleung** [comment]
Thanks for bringing this up. This is already being worked on in this PR https://github.com/freeCodeCamp/how-to-contribute-to-open-source/pull/462 and already brought up in this issue here https://github.com/freeCodeCamp/how-to-contribute-to-open-source/issues/410. It looks like you've been involved in those threads, so I'll be closing this issue in favor of those others. Happy coding!
