### ISSUE TITLE
Add React

### ISSUE THREAD

**Issue by shubheksha** [freeCodeCamp/how-to-contribute-to-open-source#9]
https://facebook.github.io/react/index.html

[Contributing guide](https://facebook.github.io/react/contributing/how-to-contribute.html)
Issue label: [good first bug](https://github.com/facebook/react/labels/good%20first%20bug)

**Comment by alfonsotech** [comment]
Hi, I'd like to work on this one but I'm not sure what needs to be done. Can you help me get started in the right direction? Thanks!

**Comment by erictleung** [comment]
@alfonsotech thanks for your interest in contributing! This issue is related to https://github.com/freeCodeCamp/how-to-contribute-to-open-source/issues/36, where we will create a separate file to hold different projects to contribute to. I've been meaning to work on this soon so others can contribute. Right now, it appears that someone else has tried to add this link already https://github.com/freeCodeCamp/how-to-contribute-to-open-source/pull/30. Once I create the separate projects file, I'll ask if that person will update their pull request to mirror the changes.

In sum, wait on the creation of a separate file for projects before making a pull request.

**Comment by 94151** [comment]
@shubheksha is this issue still open? Can i start work on it?

**Comment by erictleung** [comment]
Closed by https://github.com/freeCodeCamp/how-to-contribute-to-open-source/pull/150
